name: Test use cases on environment

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run against'
        required: true
        default: 'test'
        type: choice
        options:
        - yt01
        - test
        - staging
        - production
        - at22
        - at23
        - at24
  push:
    branches:
      - 'feat/bruksmonster-tests'  # Triggers on push to any branch

run-name: Test use cases for environment ${{ github.event.inputs.environment || 'test' }}

jobs:
  usecase-test:
    environment: ${{ github.event.inputs.environment || 'test' }}
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Run use case test (case_initialize_correspondence.js)
      uses: grafana/k6-action@e4714b734f2b0afaabeb7b4a69142745548ab9ec # v0.3.1
      env:
        base_url: ${{ secrets.CORRESPONDENCE_BASE_URL }}
        resource_id: ${{ secrets.BRUKSMONSTER_RESOURCE_ID }}
        mp_client_id: ${{ secrets.BRUKSMONSTER_MASKINPORTEN_CLIENT_ID }}
        mp_kid: ${{ secrets.BRUKSMONSTER_MASKINPORTEN_KID }}
        mp_client_pem: ${{ secrets.BRUKSMONSTER_MASKINPORTEN_PEM }}
      with:
        filename: Test/Altinn.Correspondence.UseCaseTests/case_initialize_correspondence.js

    - name: Build failure report
      if: failure()
      run: |
          report=":warning: Correspondence use case test failure :warning: \n"
          report+="\n Workflow: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "stepreport=$report" >> $GITHUB_ENV
    - name: Report failure to Slack
      if: failure()
      id: slack
      uses: slackapi/slack-github-action@91efab103c0de0a537f72a35f6b8cda0ee76bf0a # v2.1.1
      with:
        webhook-type: incoming-webhook
        webhook: ${{ secrets.SLACK_URL }}
        payload: |
          {
            "text": "${{ env.stepreport }}"
          }